name: Postman Collection Workflow

on: 
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 6 * * 1
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: SetUp NodeJs
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'

      - name: Install Newman and htmlextra library
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
             newman run 'InWarranty-Flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra
            
      - name: Newman Report
        if: always() #Ensures that it always generates the report irrespective of failures in tests
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Newman Report
          path: newman/*.html
          
